# create docker compose of  postgresqlversion: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pong
      POSTGRES_USER: pong
      POSTGRES_DB: taskmanager

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
